repo:
  - '*'

dependencies-modified:
  - package.json
  - package-lock.json

index-modified:
  - any: ['**/index.js']

sample-modified:
  - any: ['**/sample.js']

js-files-modified:
  - '**/*.js'

workflows-modified:
  - any: ['.github/**/*']

label1:
 - '*'

label2:
 - '*'

label3:
 - '*'

label4:
 - '*'

label5:
 - '*'

label6:
 - '*'

label7:
 - '*'

label8:
 - '*'

label9:
 - '*'

label10:
 - '*'

label11:
 - '*'

label12:
 - '*'

label13:
 - '*'

label14:
 - '*'

label15:
 - '*'

label16:
 - '*'

label17:
 - '*'

label18:
 - '*'

label19:
 - '*'

label20:
 - '*'

label21:
 - '*'

label22:
 - '*'

label23:
 - '*'

label24:
 - '*'

label25:
 - '*'

label26:
 - '*'

label27:
 - '*'

label28:
 - '*'

label29:
 - '*'

label30:
 - '*'

label31:
 - '*'

label32:
 - '*'

label33:
 - '*'

label34:
 - '*'

label35:
 - '*'

label36:
 - '*'

label37:
 - '*'

label38:
 - '*'

label39:
 - '*'

label40:
 - '*'

label41:
 - '*'

label42:
 - '*'

label43:
 - '*'

label44:
 - '*'

label45:
 - '*'

label46:
 - '*'

label47:
 - '*'

label48:
 - '*'

label49:
 - '*'

label50:
 - '*'

label51:
 - '*'

label52:
 - '*'

label53:
 - '*'