repo:
  - '*'

dependencies-modified:
  - any: ['**/package.json', '**/package-lock.json']

index-modified:
  - any: ['**/index.js']

sample-modified:
  - any: ['**/sample.js']

js-files-modified:
  - any: ['**/index.js', '**/sample.js']