on: [push, pull_request]

permissions: 
    checks: write
    contents: write
    packages: write

jobs:
    test-multiple-workflow-triggers:
        name: Test Multiple Workflow Triggers
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: "npm"
                registry-url: "https://npm.pkg.github.com"

            - name: Install Dependencies
              run: npm ci
              shell: bash
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Run test
              run: npm test