name: 'Test the setup-node action'

on: pull_request

jobs:
    test-setup-node:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Setup Node
              uses: dusan-trickovic/setup-node@test/cache-pkg-version
              with:
                node-version: 18.x
                cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Success
              run: echo 'Success!'
            - name: Node Version
              run: node --version