name: Labeler
on: 
  push:
  pull_request:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
    label:

        runs-on: ubuntu-latest

        permissions:
          contents: read
          pull-requests: write

        steps:

            - name: List current directory
              run: pwd

            - name: Add labels
              uses: dusan-trickovic/labeler@test/issue-562-test
              with:
                configuration-path: '.github/labeler.yml'
                sync-labels: true